### ISSUE TITLE
Multiple initialization of Mediator

### ISSUE THREAD

**Issue by isBatak** [alebianco/robotlegs-utilities-starling#1]
Hi,
I'm using your latest master commit with Feathers 2.1 BETA and having some issues.
With new StackScreenNavigator when transitioning (let's say Cover transition) to another view, first view is added to temp container (feathers/motion/Cover.as line 289) and at the same time the mediator responsible for that view is initialized for the second time, and so on for every view.

Problem could be in StageObserver line 82 and use of Event.ADDED instead of Event.ADDED_TO_STAGE. This is just assumption.

Please can you check what is the problem.
And also, sorry for my broken English :D

**Comment by alebianco** [comment]
Hi,
yes, that's an unfortunate but expected behaviour. Changing this behaviour would prevent other scenarios where you will want the mediators to be destroyed and recreated.

To avoid that I would have to implement something very specific to that feature of that framework ... which is something I'm very reluctant to do since it goes against the generic nature of the lib.

The best approach to solve your problem, I think, would be to use a custom bundle instead of the predefined one when creating the context. Then replace the standard StageObserver with your own version, which would take in consideration where the view is being added and if it's the temporary container used for transitions, avoids creating the mediator.

hope this will help finding a solution to your problem ...
